In [6]:
import sys
sys.path.append('/root/mod-decision-diffuser/code/')
sys.path.append('/root/grid2op_mod/')

In [7]:
import pandas as pd
import numpy as np

from data_encoder_decoder import load_data

In [8]:
data, _ = load_data('data/data_sampled.pkl')

In [9]:
oservations, actions = data['observations'], data['actions']

In [11]:
oservations[0][:62]

array([  2.4     ,   2.4     , 400.3     ,   0.      ,  23.      ,
        22.7     ,  84.      ,  21.4     ,   0.      ,  21.4     ,
        52.1     ,   0.      ,   7.1     , 400.3     ,   3.4     ,
         3.4     ,   0.      ,   6.6     ,   0.      ,   0.      ,
         3.5     ,   3.5     ,  21.3     ,  21.1     ,  87.4     ,
        43.2     ,   0.      ,  21.5     ,  21.7     ,   0.      ,
        44.      ,  43.2     ,   0.      ,   7.3     ,  41.9     ,
       400.1     ,   0.      ,  24.110022,   0.      ,  71.3     ,
         0.      ,   0.      ,  48.6     ,  20.3     ,  20.5     ,
        10.3     ,   0.      ,   0.      ,   7.9     ,  19.9     ,
        19.8     , 300.      ,   4.      ,  29.2     ,   4.1     ,
       149.9     ,   0.      ,   8.3     ,   0.      ,   8.6     ,
         0.      ,   0.      ], dtype=float32)

In [12]:
actions[0]

array([-2.4       , -0.8720261 ,  0.        , -0.        , -0.3210615 ,
       -1.701696  , -0.9549195 , -0.        , -0.        , -2.7832901 ,
       -0.        , -0.        , -0.        , -2.8       , -3.3044794 ,
        1.1192613 , -0.        , -0.        , -0.        , -0.        ,
       -3.5       , -2.390639  , -0.        , -0.86106706, -2.1396081 ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        , -0.        , -2.0998974 , -0.        ,
        0.        , -0.        ,  0.        , -0.        , -0.        ,
       -0.        , -0.        , -2.3152738 , -4.3226314 , -0.        ,
       -0.2891113 , -0.        , -0.        , -0.        , -2.1627648 ,
       -1.7480209 ,  0.        , -0.        , -0.492426  , -2.6522088 ,
       -0.        , -0.        , -0.        , -0.        , -0.        ,
       -0.        , -0.        ], dtype=float32)

In [19]:
oservations[0][:62] + actions[0] == oservations[1][:62]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True])

In [18]:
random_list = [np.random.randint(low=0, high=80000) for _ in range(10)]

for timestep in random_list:
    print(f"timestep: {timestep}")
    print(actions[timestep][oservations[timestep][:62] == 0])

timestep: 12790
[-0. -0. -0. -0. -0. -0.]
timestep: 72424
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
timestep: 54411
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
timestep: 55963
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0. -0. -0. -0. -0. -0.]
timestep: 36466
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.
 -0. -0. -0. -0.]
timestep: 582
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0. -0.]
timestep: 28649
[-0.         -0.         -0.         -0.         -0.          0.08477653
 -0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.08093705 -0.         -0.
  0.01433846 -0.         -0.         -0.         -0.          0.15139124
 -0.        ]
timestep: 28906
[-0. -0. -0. -0. -0. -0. -0. -0. -0. -0.

In [21]:
random_list = [np.random.randint(low=0, high=80000) for _ in range(10)]

for timestep in random_list:
    print(f"timestep: {timestep}")
    print(oservations[timestep][:62] + actions[timestep] == oservations[timestep+1][:62])

timestep: 75986
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
timestep: 41264
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
timestep: 66319
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True

In [23]:
oservations[0][161:223] == oservations[1][161:223]

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False])

In [24]:
oservations[0][161:223] 

array([ -14.748921 ,  -14.748921 ,  -92.04478  , -138.62073  ,
         25.913416 ,   25.913416 ,  100.94382  ,    6.941915 ,
         18.594582 ,    6.941915 ,   15.21488  ,   43.956272 ,
       -156.69667  ,   96.84332  ,   51.108868 ,   51.108868 ,
        -63.66118  ,    8.761029 ,    8.131785 ,   23.247894 ,
          3.602356 ,    3.602356 ,    4.002582 ,    4.002582 ,
          4.874327 ,    1.4557861,   23.688576 ,    4.5602474,
          4.5602474,   12.215057 ,   19.793842 ,   18.437796 ,
        -24.676123 ,    8.2063675,    9.118105 ,  220.17079  ,
       -217.15305  , -234.95625  ,   56.388496 ,  -14.631455 ,
         54.463333 ,   30.208773 ,   37.760967 ,  -40.087284 ,
        -40.087284 ,   69.4241   ,   57.523857 ,    4.5362134,
         12.217419 ,   32.190834 ,   32.190834 ,   26.973503 ,
          8.354357 ,   62.160397 ,    8.354357 ,    1.475405 ,
         67.28459  ,   30.60838  ,   12.965913 ,   40.145348 ,
        -25.493229 ,  197.32422  ], dtype=float32)

In [25]:
oservations[1][161:223]

array([ -14.606089 ,  -14.606089 ,  -92.24981  , -138.62073  ,
         26.568287 ,   26.568287 ,  100.18981  ,    7.2717366,
         19.478039 ,    7.2717366,   15.064976 ,   43.45647  ,
       -157.32968  ,   96.49051  ,   51.18858  ,   51.18858  ,
        -64.47408  ,    8.528595 ,    7.864567 ,   22.874043 ,
          3.9143858,    3.9143858,    4.349279 ,    4.349279 ,
          4.9389668,    1.4750916,   24.254076 ,    4.5153003,
          4.5153003,   12.094662 ,   19.77284  ,   19.208948 ,
        -24.874819 ,    8.208092 ,    9.120021 ,  219.03308  ,
       -217.53926  , -240.10466  ,   55.19998  ,  -14.895313 ,
         54.347546 ,   30.943708 ,   38.679634 ,  -39.33453  ,
        -39.33453  ,   69.929085 ,   57.813175 ,    4.39741  ,
         12.235724 ,   32.823406 ,   32.823406 ,   27.55194  ,
          8.553126 ,   63.63933  ,    8.553126 ,    1.6889188,
         67.47941  ,   30.818672 ,   12.8389635,   39.85433  ,
        -25.733044 ,  196.23     ], dtype=float32)

In [26]:
oservations[0][161:223].shape

(62,)

In [28]:
oservations[0][223:409] 

array([6.7935281e-07, 1.2243569e-06, 1.8238270e-06, 4.1796570e-06,
       1.4792846e-06, 1.3561554e-06, 2.8323559e-06, 1.9684107e-06,
       1.8443943e-06, 1.9972483e-06, 1.0211103e-06, 1.0084126e-07,
       3.9998931e-06, 1.3359378e-06, 9.7422082e-07, 1.7304747e-06,
       2.3177702e-07, 3.4687602e-07, 1.6671387e-07, 5.9916277e-07,
       4.2464794e-06, 3.3748013e-06, 7.1382880e-07, 8.2982825e-07,
       6.9779679e-07, 4.8561031e-07, 9.3160088e-07, 7.0766021e-07,
       9.9116892e-07, 2.3243031e-06, 3.9625701e-07, 7.5350334e-07,
       9.8555688e-07, 3.0031040e-06, 9.3636010e-07, 1.1200769e-06,
       1.0083721e-06, 1.2662030e-06, 9.9138629e-07, 7.0157898e-07,
       1.1201998e-06, 2.0440243e-06, 5.5373800e-07, 6.7812078e-07,
       2.1805708e-06, 2.0128496e-06, 1.5949087e-06, 1.6947723e-06,
       6.7651496e-07, 1.8246957e-06, 1.3822332e-06, 1.9192898e-06,
       1.4945612e-06, 1.6389453e-06, 3.8252901e-07, 1.1781083e-06,
       1.0012221e-06, 1.1319180e-06, 2.5415131e-06, 3.3435072e